server:
  port: 8081
  servlet:
    context-path: /admin
  
spring:
  datasource:
    url: jdbc:mysql://172.17.19.13:3306/test
    username: admin
    password: admin
    
  jpa:
    hibernate:
      use-new-id-generator-mappings: true